# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: 'energy-origin-bot/action-receiver'
          ssh-key: ${{ secrets.PRIVATE_KEY_TRANSMITTER_RECEIVER_EXP }}  

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Jakob magic
        run: head -c 500 /dev/urandom | tr -dc 'a-zA-Z0-9~!@#$%^&*_-' | head -n 1 > random.file

      - name: Commit changes
        uses: EndBug/add-and-commit@v7 
        with:
          add: '["random.file"]'
          message: "Random magic from Jakob - Welcome to the dark side"
          push: true
          branch: main
